[ids]
*

[main]
capslock = leftcontrol
leftcontrol = leftmeta
# capslock = layer(control)
# leftcontrol = layer(meta)
pageup = left
pagedown = right
# k = oneshotk(after_k, k)

f1 = M-up
f2 = M-left
f3 = M-right

[after_k]
j = macro(backspace esc esc)

[control]
#m = M-m

